# Generated by Django 6.0.1 on 2026-01-26 12:41

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('category', models.CharField(choices=[('corporate', 'Корпоративное право'), ('family', 'Семейное право'), ('criminal', 'Уголовное право'), ('civil', 'Гражданское право'), ('tax', 'Налоговое право'), ('labor', 'Трудовое право'), ('property', 'Недвижимость'), ('inheritance', 'Наследственное право'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена от')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена до')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Сроки выполнения')),
                ('icon', models.CharField(blank=True, default='bi-briefcase', max_length=100, verbose_name='Иконка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая услуга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LawyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('lawyer', 'Юрист'), ('senior_lawyer', 'Старший юрист'), ('leading_lawyer', 'Ведущий юрист'), ('partner', 'Партнер'), ('senior_partner', 'Старший партнер'), ('head', 'Руководитель направления')], default='lawyer', max_length=50, verbose_name='Должность')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('bio', ckeditor.fields.RichTextField(help_text='Подробная информация о юристе', verbose_name='Биография')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж работы (лет)')),
                ('education', models.TextField(verbose_name='Образование')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(help_text='Формат: +7 XXX XXX-XX-XX', max_length=20, verbose_name='Телефон')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='Кабинет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lawyers/', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показать на главной')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('vk_link', models.URLField(blank=True, verbose_name='Ссылка на VK')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('services', models.ManyToManyField(blank=True, related_name='lawyers', to='lawyer_site.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Юрист',
                'verbose_name_plural': 'Юристы',
                'ordering': ['order', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сертификата')),
                ('issuer', models.CharField(max_length=200, verbose_name='Организация-выдаватель')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Номер сертификата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Файл сертификата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/images/', verbose_name='Изображение сертификата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='lawyer_site.lawyerinfo', verbose_name='Юрист')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Ответ')),
                ('category', models.CharField(choices=[('general', 'Общие вопросы'), ('services', 'Вопросы об услугах'), ('prices', 'Цены и оплата'), ('process', 'Процесс работы'), ('documents', 'Документы'), ('other', 'Другое')], default='general', max_length=50, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_general', models.BooleanField(default=False, help_text='Будет отображаться на главной странице FAQ', verbose_name='Общий вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='lawyer_site.service', verbose_name='Связанная услуга')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['category', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('request_type', models.CharField(choices=[('consultation', 'Консультация'), ('service', 'Заказ услуги'), ('callback', 'Обратный звонок'), ('complaint', 'Жалоба'), ('other', 'Другое')], default='consultation', max_length=20, verbose_name='Тип запроса')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyer_site.lawyerinfo', verbose_name='Предпочтительный юрист')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyer_site.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запрос с формы',
                'verbose_name_plural': 'Запросы с формы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название дела')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('client', models.CharField(help_text='Имя или организация клиента', max_length=200, verbose_name='Клиент')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание ситуации')),
                ('challenge', ckeditor.fields.RichTextField(help_text='С какими трудностями столкнулись', verbose_name='Проблема/Задача')),
                ('solution', ckeditor.fields.RichTextField(verbose_name='Решение')),
                ('result', ckeditor.fields.RichTextField(verbose_name='Результат')),
                ('case_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата завершения дела')),
                ('duration_months', models.PositiveIntegerField(default=1, verbose_name='Продолжительность (месяцев)')),
                ('status', models.CharField(choices=[('completed', 'Завершено успешно'), ('in_progress', 'В процессе'), ('pending', 'Ожидает рассмотрения')], default='completed', max_length=20, verbose_name='Статус')),
                ('complexity', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Сложность дела (1-10)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показать на главной')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lawyers', models.ManyToManyField(related_name='cases', to='lawyer_site.lawyerinfo', verbose_name='Юристы')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='lawyer_site.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Дело/Кейс',
                'verbose_name_plural': 'Дела/Кейсы',
                'ordering': ['-case_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('category', models.CharField(choices=[('news', 'Новости'), ('analytics', 'Аналитика'), ('tips', 'Советы'), ('legislation', 'Законодательство'), ('practice', 'Судебная практика')], default='news', max_length=50, verbose_name='Категория')),
                ('excerpt', models.CharField(help_text='Отображается в списке статей', max_length=300, verbose_name='Краткое описание')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Главное изображение')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/', verbose_name='Миниатюра')),
                ('tags', models.CharField(blank=True, help_text='Через запятую', max_length=200, verbose_name='Теги')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая статья')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Время чтения (минут)')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='lawyer_site.lawyerinfo', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'category'], name='lawyer_site_is_publ_c3a56f_idx'), models.Index(fields=['author', 'published_at'], name='lawyer_site_author__cee53d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lawyerinfo',
            index=models.Index(fields=['is_active', 'is_featured'], name='lawyer_site_is_acti_3db68a_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyerinfo',
            index=models.Index(fields=['position', 'experience_years'], name='lawyer_site_positio_4331ec_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_active'], name='lawyer_site_categor_fdc0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_general', 'order'], name='lawyer_site_is_gene_5e94c0_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['status', 'is_processed'], name='lawyer_site_status_772b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['request_type', 'created_at'], name='lawyer_site_request_c607e3_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'is_published'], name='lawyer_site_status_44069f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['service', 'case_date'], name='lawyer_site_service_92d297_idx'),
        ),
    ]
